# src/main/resources/application-prod.yml
spring:
  config:
    activate:
      on-profile: prod
  # Cấu hình datasource cho production
  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USER}
    password: ${PROD_DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # Tắt Swagger trên production
  springdoc:
    api-docs:
      enabled: false
    swagger-ui:
      enabled: false