# src/main/resources/application.yml
server:
  port: 8081

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: backend-service
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/backend-service?useSSL=false&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
  sendGrid:
    apiKey: ${SENDGRID_API_KEY}
    fromEmail: ${SENDGRID_FROM_EMAIL:noreply@example.com}
    templateId: ${SENDGRID_TEMPLATE_ID}
    verificationLink: ${VERIFICATION_LINK:http://localhost:8081/user/confirm-email}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    root: INFO
    web: INFO
    vn.thanhquan: DEBUG # Bật debug log cho package của bạn

# Cấu hình Swagger/OpenAPI chung
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: backend-service
    server: http://localhost:${server.port}
    title: Backend service
    version: 1.0.0

# Cấu hình JWT
jwt:
  secret:
    access-key: ${JWT_ACCESS_KEY:ZHVtbXktYWNjZXNzLXNlY3JldC1rZXktZm9yLWRldmVsb3BtZW50MTIzNDU2Nzg5MGFiY2RlZmdoaWo=} # Sử dụng biến môi trường
    refresh-key: ${JWT_REFRESH_KEY:ZHVtbXktcmVmcmVzaC1zZWNyZXQta2V5LWZvci1kZXZlbG9wbWVudDEyMzQ1Njc4OTBhYmNkZWZnaGo=} # Sử dụng biến môi trường