version: '3.8'

services:
  # MySQL Database Service
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: backend-service
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD:-password}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Backend Service Application
  backend-service:
    container_name: backend-service
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8081"
    networks:
      - my_network
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      # Spring Profile
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}
      
      # Database Configuration
      - DB_URL=jdbc:mysql://mysql:3306/backend-service?useSSL=false&serverTimezone=UTC
      - DB_USERNAME=root
      - DB_PASSWORD=${DB_PASSWORD:-password}
      
      # JWT Configuration
      - JWT_ACCESS_KEY=${JWT_ACCESS_KEY}
      - JWT_REFRESH_KEY=${JWT_REFRESH_KEY}
      
      # SendGrid Configuration
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - SENDGRID_FROM_EMAIL=${SENDGRID_FROM_EMAIL}
      - SENDGRID_TEMPLATE_ID=${SENDGRID_TEMPLATE_ID}
      - VERIFICATION_LINK=${VERIFICATION_LINK:-http://localhost:8081/user/confirm-email}
      
      # CORS Configuration
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost:3000,http://localhost:4200}
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s

# Định nghĩa volumes và networks để quản lý tập trung
volumes:
  mysql_data:


networks:
  my_network:
    driver: bridge
